### ISSUE TITLE
Disqus can't be loaded.

### ISSUE THREAD

**Issue by shawlang** [ppoffice/hexo-theme-minos#1]
I added the `disqus_shortname:shawlang ` to the _config.yml, but Disqus can't be loaded.
The error is 
>we are unable to load Disqus. If you are a moderator please see our troubleshooting....

Then I copyed the universal code from Disqus to the end of file "article.ejs".It works.
I think there is something wrong the code of Minos.

**Comment by ppoffice** [comment]
Which _config.yml did you put `disqus_shortname:shawlang` in? I think the problem may have something to do with your config. And the Disqus script is in the `after-footer.ejs`, you can compare it to your universal code to find out the differences that may help to solve the problem.

**Comment by shawlang** [comment]
I put it into the global _config.yml.(not into themes/_config.yml).
I compare the universal code to the code of after-footer.ejs. They are almost the same.

**Comment by shawlang** [comment]
I put it into the global _config.yml.(not into themes/_config.yml).
I compared the universal code to the code of after-footer.ejs. They are almost the same. I cannot figure it out.

###### 1. after-footer.ejs

```
<script>
  var disqus_shortname = '<%= config.disqus_shortname %>';
  <% if (page.permalink){ %>
  var disqus_url = '<%= page.permalink %>';
  <% } %>
  (function(){
    var dsq = document.createElement('script');
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/<% if (page.comments) { %>embed.js<% } else { %>count.js<% } %>';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script> 
```

###### 2. universal code

```
 <div id="disqus_thread"></div>
  <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'shawlang';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 

'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || 

document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script> 
```

**Comment by ppoffice** [comment]
Please add `var disqus_developer = 1;` to the original `after-footer.ejs` Disqus script and see if anything changes, or you may want to check your Disqus site config to see if there exists any block rules.

**Comment by shawlang** [comment]
nothing changed. It exists the same error.This is my blog website : [shawlang.github.io](http://shawlang.github.io)

There're no special block rules here : [Disqus universal code](https://shawlang.disqus.com/admin/settings/universalcode/)

**Comment by ppoffice** [comment]
I think I found the problem: your are using relative `disqus_url` in your post. According to https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22, `disqus_url must use an absolute URL; relative URLs won’t work. E.g.`, so you need to edit your Disqus config and add `http://` before your site url.

**Comment by shawlang** [comment]
Thanks. You are right. But I fixed the problem by rewrite the URL in the global _config.yml of Hexo,not  edited it in the Disqus config. 
#### correct: 
>url: http://shawlang.github.io

#### incorrect
>url: shawlang.github.io

That can be explained.
```
var disqus_url = '<%= page.permalink %>';
```
In fact, disqus_url needs the absolute link which consists of "http://",and the prefix of page.permalink is provided by global _config.yml. So if the prefix is right,disqus_url will be right.

Thanks again for not only helping me fix the problem but also stand bad English! :smile:
