### ISSUE TITLE
some Plugin Problems

### ISSUE THREAD

**Issue by GerhardMes** [ppoffice/hexo-theme-minos#102]
Hello,
I have some problems especially with the  isn't working at all; and the gallery plugin sometimes functions perfectly and sometimes not at all.

Any hint how I can fix this?
Nice weekend and Cheers. Gerhard

**Comment by ppoffice** [comment]
@GerhardMes Please give more details

**Comment by liudixian** [comment]
I have the same problem...

<img width="590" alt="屏幕快照 2019-06-15 上午3 34 56" src="https://user-images.githubusercontent.com/11694349/59533606-9c903c80-8f1e-11e9-98e2-7fca8dd1f5ec.png">

but the result  is that 

<img width="928" alt="屏幕快照 2019-06-15 上午3 35 59" src="https://user-images.githubusercontent.com/11694349/59533640-b7fb4780-8f1e-11e9-8968-db10a61fd2dc.png">

**Comment by ppoffice** [comment]
@GerhardMes You cannot use Markdown inside HTML tags.

**Comment by Simon-Leung** [comment]
> @GerhardMes You cannot use Markdown inside HTML tags.

but the [Creating-a-Gallery-in-Minos.md](https://raw.githubusercontent.com/ppoffice/hexo-theme-minos/site/source/_posts/Creating-a-Gallery-in-Minos.md) use markdown inside html tags
