### ISSUE TITLE
Using Netlify to deploy, Insight Search Chinese garbled.

### ISSUE THREAD

**Issue by hijulian** [ppoffice/hexo-theme-minos#108]
Using Netlify to deploy, Insight Search Chinese garbled.
![image](https://user-images.githubusercontent.com/6925683/74581079-11ec6980-4fe6-11ea-9134-a3f206637769.png)

**Comment by ppoffice** [comment]
@hijulian Can you show me your netlify url?

**Comment by hijulian** [comment]
https://blog.changjujian.com/

**Comment by hijulian** [comment]
https://pm.changjujian.com/

**Comment by hijulian** [comment]
The problem persists, what do I need to do to resolve it.

**Comment by hijulian** [comment]
It's normal now, thank you for the beautiful theme.
