### ISSUE TITLE
How to change default renderer

### ISSUE THREAD

**Issue by Nautilus-N** [ppoffice/hexo-theme-minos#109]
When I
1. Uninstall the default renderer(hexo-renderer-marked)
2. Install another renderer(such as "hexo-renderer-kramed") 
3. Use hexo command "hexo clean"

It will report:
**INFO  Checking dependencies
ERROR Package hexo-renderer-marked is not installed.
ERROR Please install the missing dependencies in the root directory of your Hexo site.**

**Comment by ppoffice** [comment]
@Nautilus-N Comment out this line should work
https://github.com/ppoffice/hexo-theme-minos/blob/master/scripts/01_check.js#L37

**Comment by Nautilus-N** [comment]
Thanks! It works for me. :)
