### ISSUE TITLE
a problem with the table presentation in markdown document

### ISSUE THREAD

**Issue by WanZixin** [ppoffice/hexo-theme-minos#111]
This is what the table shows in the blog. But I want to show the table this way.![批注 2020-05-25 174509](https://user-images.githubusercontent.com/43515397/82801416-dd732e00-9eaf-11ea-9072-85eae9280d21.png)
![批注 2020-05-25 175145](https://user-images.githubusercontent.com/43515397/82801773-6c804600-9eb0-11ea-8256-af1f32426a65.png)

**Comment by ppoffice** [comment]
@WanZixin please enable gfm in your site's config.yml

https://github.com/hexojs/hexo-renderer-marked/blob/master/README.md#options

**Comment by WanZixin** [comment]
@ppoffice Thank you. It worked as you said. Besides, I also used some CSS to style the table.
![批注 2020-05-26 100551](https://user-images.githubusercontent.com/43515397/82853601-c298cc00-9f38-11ea-8c13-9def619166bf.png)
![批注 2020-05-26 100633](https://user-images.githubusercontent.com/43515397/82853657-e4924e80-9f38-11ea-9feb-788082c53120.png)
