### ISSUE TITLE
I Can't use Tag Plugin

### ISSUE THREAD

**Issue by LeiWang1999** [ppoffice/hexo-theme-minos#113]
Actually I wanna archive such effect: Show Image on excerpt
I saw your solutions in here : https://blog.zhangruipeng.me/hexo-theme-minos/Using-Hexo-Tag-Plugins-in-Minos/
But i cann't use every tag plugins!
Error like this:
> Unhandled rejection Nunjucks Error:  [Line 2, Column 4] unknown block tag: centerquote

**Comment by ppoffice** [comment]
@LeiWang1999 There's no tag plugin called `centerquote`

**Comment by LeiWang1999** [comment]
Oh! Thank u, That tag plugin can only be used in `NexT` theme, But i wanna show image in article, use sentence below:
`
![](http://leiblog.wang/static/image/2020/6/mountain.jpg)
<img src="http://leiblog.wang/static/image/2020/6/mountain.jpg"></img>
`
It cannot be shown in home excerpt, I search some solutions include 
{% asset_img"http://leiblog.wang/static/image/2020/6/mountain.jpg" banner %}
But it does'nt even work in markdown!

**Comment by LeiWang1999** [comment]
My intuition says it is because excerpt uses a different page generation process than the normal post. 
Can you tell me how you used the excerpt in your Demo page, I tried the another auto-excerpt plugin.

**Comment by ppoffice** [comment]
@LeiWang1999 https://hexo.io/docs/tag-plugins#Post-Excerpt
https://raw.githubusercontent.com/ppoffice/hexo-theme-minos/site/source/_posts/Configuring-Minos.md

**Comment by LeiWang1999** [comment]
@ppoffice Awesome! Thank u very much!
