### ISSUE TITLE
本地启动后样式失效了

### ISSUE THREAD

**Issue by WanZixin** [ppoffice/hexo-theme-minos#119]
本来应该是这样
![image](https://user-images.githubusercontent.com/43515397/115133207-f8570f80-a038-11eb-9406-9853dbdcd4c2.png)
结果现在是这样了
![image](https://user-images.githubusercontent.com/43515397/115133217-086eef00-a039-11eb-8020-9cc9a45c2996.png)
应该用什么办法解决

**Comment by ppoffice** [comment]
@WanZixin 在浏览器中按F12打开开发者面板，在其中切换到Network(网络)标签页观察哪些资源没有加载（红色的条目）。

![image](https://user-images.githubusercontent.com/8849362/115263594-8bf51280-a103-11eb-9e65-2b0097e7a4e7.png)

**Comment by WanZixin** [comment]
几个css文件http状态码成307了，可能是这的问题吧，但是不知道怎么解决了
![image](https://user-images.githubusercontent.com/43515397/115552378-da123d80-a2de-11eb-8696-19b3b85ef742.png)

**Comment by ppoffice** [comment]
你有修改主题的布局或者样式表文件么？如果有的话，确保布局文件的html和样式表没有语法错误。

**Comment by WanZixin** [comment]
好的，我修改过配置文件，明天我检查一下有没有语法错误

**Comment by WanZixin** [comment]
@ppoffice 你好，我这边已经解决了，谢谢你的解答
