### ISSUE TITLE
手机端菜单显示

### ISSUE THREAD

**Issue by zhuoshuai** [ppoffice/hexo-theme-minos#13]
在手机端菜单显示只是在左侧 一个带有三个横杠的 按钮 ，点击它就返回主页，点击中间的空格菜单 也亦返回主页，手机端将电脑端的 菜单显示完全怎么办？

**Comment by ppoffice** [comment]
应该是你的JS脚本没有完全加载。尝试下清空缓存？

**Comment by zhuoshuai** [comment]
系统iOS7.1.2 用的Safari ，我刚才把手机端的cookies和数据清除了，但问题依旧n


—

**Comment by ppoffice** [comment]
我大概知道什么原因了，晚上搞定

**Comment by rosingle** [comment]
这个已经解决了嘛，我看那个示范网站还是一样啊
