### ISSUE TITLE
Add support for table of contents?

### ISSUE THREAD

**Issue by jbcpollak** [ppoffice/hexo-theme-minos#16]
Does Minos support rendering a table of contents, like in https://github.com/hexojs/hexo/issues/408?

It looks like tranquilpeak supports the TOC by using a `<!-- toc -->` tag: 

https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#display-table-of-contents

**Comment by ppoffice** [comment]
Just add 
```
toc: true
```
in your theme's `_config.yml` file to enable `toc`.
