### ISSUE TITLE
请问如何设置head.ejs中图标favicon？

### ISSUE THREAD

**Issue by sincerexie** [ppoffice/hexo-theme-minos#17]
怎么试都没有成功，能不能告知下方法

**Comment by ppoffice** [comment]
替换下[/source/css/images/logo.png](https://github.com/ppoffice/hexo-theme-minos/blob/master/source/css/images/logo.png)

**Comment by sincerexie** [comment]
谢谢，已经没问题了，是我的chrome出了问题，设置是成功的。
