### ISSUE TITLE
如何添加disqus评论？

### ISSUE THREAD

**Issue by theqwang** [ppoffice/hexo-theme-minos#19]
您好，很喜欢这个主题！可是我安装以后怎么没有demo里的disqus评论了呢，求告知怎么添加disqus，感谢！

**Comment by ppoffice** [comment]
我帮你Google了一下。
http://guoshuang.com/hexo/hexo%E5%8A%A0%E8%AF%84%E8%AE%BA/
这种问题举手之劳……

**Comment by charsdavy** [comment]
无效！！！！！之前用yilia主题没有问题

**Comment by ppoffice** [comment]
@charsdavy 可能是Disqus更新了评论代码，以标记Bug，待修复
