### ISSUE TITLE
移动端视频不能自适应，窗口显示不完整

### ISSUE THREAD

**Issue by iczbl** [ppoffice/hexo-theme-minos#2]
文章里包含youtube视频，在手机端不能自适应分辨率，而且窗口不能完整显示，
视频代码`<iframe width="560" height="315" src="https://www.youtube.com/embed/-YGDyPAwQz0" frameborder="0" allowfullscreen></iframe>`
使用android默认浏览器和chrome均有次问题

**Comment by ppoffice** [comment]
由于不同视频网站的播放器默认大小可能是不一样的，所以统一在主题css里面规定是复杂而且并没有什么卵用的。。。所以这里给你一个临时解决方法吧：
```html
<div style="height: 0;padding-bottom: 56%;position: relative;">
<iframe width="560" height="315" src="https://www.youtube.com/embed/-YGDyPAwQz0" frameborder="0" allowfullscreen="" style="position: absolute;height: 100%;width: 100%;"></iframe>
</div>
```
把这个插入到你原来插入iframe的位置。其中div的56%就是你播放器应该有的宽高比。

**Comment by iczbl** [comment]
@ppoffice 
呃..宽高比正常，但是播放器窗口超出屏幕的部分显示不了，直接在中间被剪掉了，往左也拖动不了

![yy](https://i.imgur.com/ufAaicI.png)

**Comment by ppoffice** [comment]
可以给一个网址么？我去观察下

**Comment by iczbl** [comment]
https://z-bl.com/2015/02/16/Sex-with-The-Hulk/

**Comment by ppoffice** [comment]
我看了一下你的地址，现在应该是已经好了。至于Android上如果还是显示不全的话，应该是浏览器版本过低的问题了。
同时欢迎你把解决方案pull-request过来
