### ISSUE TITLE
怎样添加“多说”评论？

### ISSUE THREAD

**Issue by myskn** [ppoffice/hexo-theme-minos#20]
主题配置文件里好像没有？
想手动添加，不知道要添加到哪个文件里？

**Comment by ppoffice** [comment]
暂时没有添加多说评论的功能，不过你可以参照着下面两个文件修改：
https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/_partial/article.ejs#L47
https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/_partial/after-footer.ejs#L1

**Comment by myskn** [comment]
解决了
http://dev.duoshuo.com/threads/541d3b2b40b5abcd2e4df0e9
