### ISSUE TITLE
请问搜索栏的搜索地址如何更改？

### ISSUE THREAD

**Issue by hidasia** [ppoffice/hexo-theme-minos#22]
我的github pages绑定了一个cname域名。
minos主题的默认搜索站点是 xxx.github.io 但是google显示不出来任何搜索结果，若改成：关键字 site:http://x.zyx.im google才会搜索出站点的相关内容。
请问如何将搜索地址由xxx.github.io 改成我自己的域名？
源码看了老半天 不知从何下手…

谢谢！

**Comment by ppoffice** [comment]
修改博客根目录的_config.yml中的url为你的自定义域名试试

**Comment by TellH** [comment]
@ppoffice 有没有实现本地站内搜索功能的计划？http://moxfive.xyz/2016/05/31/hexo-local-search/

**Comment by ppoffice** [comment]
@TellH 暂时没有计划
