### ISSUE TITLE
请教如何设置首页只显示文章标题和时间等信息，而不显示正文内容

### ISSUE THREAD

**Issue by justjump** [ppoffice/hexo-theme-minos#23]
如题。
非常感谢。

**Comment by ppoffice** [comment]
如果所有文章都要求这样的话只能去改主题的布局文件。
https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/_partial/archive.ejs#L71
改成`<%- partial('article-post', {post: post, index: true}) %>`。（我没有测试过）
否则把`<!--more-->`标签插入到正文第一行就行了。

**Comment by justjump** [comment]
加入可以了.谢谢.
