### ISSUE TITLE
留言功能？

### ISSUE THREAD

**Issue by joey3060** [ppoffice/hexo-theme-minos#24]
作者您好
很高興您做出這麼有質感的主題，我們也很喜歡。
只是不知道您有沒有多加留言的功能呢？

我自己是Google許久，嘗試許多方式，還是無法看到留言功能出現ＱＱ

**Comment by ppoffice** [comment]
@joey3060 
目前可以用disqus，其他的暂时没加上，不过网上有添加的教程
