### ISSUE TITLE
无法打开链接

### ISSUE THREAD

**Issue by charsdavy** [ppoffice/hexo-theme-minos#27]
最近两天使用这个theme直接无法使用http打开链接了，本来以为是github的问题。换了theme才知道，是minos的问题，但是无法排查，请看看是什么问题。

**Comment by ppoffice** [comment]
@charsdavy 
可能是Minos依赖的JavaScript文件或者样式表没有加载？请尝试挂代理访问

**Comment by charsdavy** [comment]
使用http不能打开链接，使用https却可以。应该不是资源的问题吧。

**Comment by ppoffice** [comment]
@charsdavy 
请在不能打开的界面上按下F12切换到console查看错误信息

**Comment by charsdavy** [comment]
现在又复现不了了，下次再出现，我尽量把console错误信息贴上来。
