### ISSUE TITLE
Read More？

### ISSUE THREAD

**Issue by liuyimx** [ppoffice/hexo-theme-minos#28]
作者你好：
我的首页文章列表中，把文章的所有内容都输出了。
我想要像你的例子里那样，展示出来一部分，然后有一个“文章详情”的链接，可是在你的配置说明中没有找到。
是在其他地方配置吗？

**Comment by ppoffice** [comment]
@liuyimx 
在你的Markdown里面添加：
```html
<!-- more -->
```

**Comment by Logan1x** [comment]
@ppoffice  You should add this to wiki page 😂😂
