### ISSUE TITLE
如何添加社交网络的小logo链接

### ISSUE THREAD

**Issue by Hugh-Shu-Wang** [ppoffice/hexo-theme-minos#33]
您好，我想把linkedin，facebook等社交网络的链接放在网站的下面，就是powered by hexo的旁边，然后通过小图标点击，请问如何做？

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/_partial/footer.ejs

自行添加FontAwesome里面的图标

**Comment by Hugh-Shu-Wang** [comment]
谢谢！还有一个问题：请问如何在文章副标题（日期，分类）的地方加上其他东西？比如我想加上访问量
