### ISSUE TITLE
Error When Run Hexo

### ISSUE THREAD

**Issue by strawoo** [ppoffice/hexo-theme-minos#42]
Hello. I got a problem when run Hexo after install minox
  
Error
`Script ERROR Script load failed: themes/minos/scripts/01_check.js
ReferenceError: hexo is not defined`

Hexo version

hexo: 3.7.1
hexo-cli: 1.1.0

Why this error Occur?

**Comment by ppoffice** [comment]
@strawoo Could you please fetch the latest master branch and test if the problem still shows up. If it is, please attack the full error log and your package.json file. Thank you.

**Comment by strawoo** [comment]
Thank you for your appreciation. It's running!.
