### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by leofo** [ppoffice/hexo-theme-minos#44]
`DEPRECATION WARNING on line 5, column 8 of D:/05_Server/02_blog/me/themes/minos/                                                                                                                                  source/css/style.scss:
Including .css files with @import is non-standard behaviour which will be remove                                                                                                                                  d in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations doc                                                                                                                                  umentation on how to create a custom importer.`

**Comment by leofo** [comment]
DEPRECATION WARNING on line 5, column 8 of D:/05_Server/02_blog/me/themes/minos/                                                                                                                                  source/css/style.scss:
Including .css files with @import is non-standard behaviour which will be remove                                                                                                                                  d in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations doc                                                                                                                                  umentation on how to create a custom importer.

**Comment by ppoffice** [comment]
@leofo Thanks for the information.

**Comment by ppoffice** [comment]
@leofo Now the highlight theme is loaded from CDN by specifying its names in the configuration file.
https://github.com/ppoffice/hexo-theme-minos/blob/master/_config.yml.example#L22
