### ISSUE TITLE
导航栏等其他内容均不显示

### ISSUE THREAD

**Issue by taiyuanhang** [ppoffice/hexo-theme-minos#45]
你好，我将源码上传到GitHub，再从GitHub下载，会导致导航栏、搜索功能、评论功能消失。
还请看下我的仓库，它在source分支。

**Comment by ppoffice** [comment]
@taiyuanhang 主题的`_config.yml`默认是被gitignore掉的，所以上传到GitHub上的没有主题配置文件。你需要修改.gitignore来确保上传这个文件。

https://github.com/taiyuanhang/taiyuanhang.github.io/blob/source/themes/minos/.gitignore#L1

**Comment by taiyuanhang** [comment]
@ppoffice 已经解决，谢谢。
