### ISSUE TITLE
可以更新个适配的TOC吗

### ISSUE THREAD

**Issue by inspiringz** [ppoffice/hexo-theme-minos#48]

**Comment by ppoffice** [comment]
@inspiringz 
在文章markdown文件头部加入`toc: true`即可。

请参考
https://blog.zhangruipeng.me/hexo-theme-minos/Writing-Math-Formulas-Using-MathJax/
https://github.com/ppoffice/hexo-theme-minos/edit/site/source/_posts/Writing-Math-Formulas-Using-MathJax.md 第八行

**Comment by inspiringz** [comment]
已解决 感谢！
