### ISSUE TITLE
Markdown blockquotes syntax doesn't work as usual.

### ISSUE THREAD

**Issue by shawlang** [ppoffice/hexo-theme-minos#5]
When I write posts like this:
![](https://s3.amazonaws.com/f.cl.ly/items/0Z120f0d1V3K0z0t2d1c/quote2.png)
But the result in post is like this:
![](https://s3.amazonaws.com/f.cl.ly/items/1q0o1K1d3j2Z2V122M1c/quote.png)
I think it should be like this:
>  It worked!
> Congratulations on your first Django-powered page.

So what's the problem with theme?  This is my  [post website:](http://shawlang.github.io/2015/07/01/Windows%E7%8E%AF%E5%A2%83%E4%B8%8Bdjango%E5%BC%80%E5%8F%91%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/) 
Thanks in advance!

**Comment by ppoffice** [comment]
It's just a unique blockquote style for minos theme. You can edit `minos/source/css/_partial/article.styl` to get a left-bordered blockquote style.

**Comment by shawlang** [comment]
How can I make it like default style or github style?

**Comment by shawlang** [comment]
Thanks to your help,I had created a new style like this by myself.
![](https://s3.amazonaws.com/f.cl.ly/items/0o232E0Y3h240a241b3S/quote3.png)
