### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by neptoo** [ppoffice/hexo-theme-minos#52]
运行时报错
DEPRECATION WARNING on line 5, column 8 of D:/hexo/themes/minos/source/css/style.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.
请问这个怎么解决？

**Comment by ppoffice** [comment]
@neptoo 请更新至最新版本的minos

**Comment by neptoo** [comment]
好的 解决了
