### ISSUE TITLE
Display on mobile phone

### ISSUE THREAD

**Issue by LC-Lin** [ppoffice/hexo-theme-minos#61]
Hello! I really think that it is a good hexo theme which stands out. And I have tried it in my blog.
But there are some problems.
Firstly, the search button and the button linking to github become a blank block on my mobile phone.
Secondly, I tried 'mathjax: true' but failed and I chose hexo-math plugin using mathjax engine. But in the html-css output format, I think its output's size is smaller. How can I sovle it?
Finally, I am an English learner and there may be some grammar mistakes. I am sorry for this. Thanks!

**Comment by ppoffice** [comment]
@LC-Lin It seems like the third-party libraries this theme includes failed to load. Is this problem also happening on your desktop PC? And could you please give me the URL of your blog so I can test it on my phone as well? Thanks.

**Comment by LC-Lin** [comment]
@ppoffice On my desktop PC, it displays as expected. This is [my blog](http://hexo.lcmain.top). [Your website](https://blog.zhangruipeng.me/hexo-theme-minos/) on my mobile phone has the problem as well.
Here is a screenshot. Thanks.

![screenshot_2018-09-01-12-22-03_com tencent mtt](https://user-images.githubusercontent.com/19491577/44942537-fe474600-ade5-11e8-8199-06908816b5be.png)

**Comment by ppoffice** [comment]
@LC-Lin What mobile browser are you using?

**Comment by LC-Lin** [comment]
@ppoffice QQ Browser

**Comment by LC-Lin** [comment]
@ppoffice I try it on another mobile browser on my phone and it is normal.

**Comment by LC-Lin** [comment]
@ppoffice No, I use its normal mode. I haven't done anything but there is no problem now.

**Comment by LC-Lin** [comment]
@ppoffice Do you think the network is the cause? You said

>  It seems like the third-party libraries this theme includes failed to load.

 I am in China. If I can change the CDN, do you think it will become better?

**Comment by ppoffice** [comment]
@LC-Lin 
Probably. You can switch to a different CDN by editting https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/common/head.ejs and https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/common/scripts.ejs

**Comment by LC-Lin** [comment]
@ppoffice OK. Thanks!

**Comment by LC-Lin** [comment]
I solve the other problem by reading your source code.
Thank you!
