### ISSUE TITLE
[Feature Request] Copyright Section

### ISSUE THREAD

**Issue by liurui39660** [ppoffice/hexo-theme-minos#62]
Hi, 
I'm just getting started using this theme.
My previous theme contains a copyright claim section, which helps my reader know whether they can reuse my post.
But I haven't found that in minos.
If there is any plan for implementing this feature?

**Comment by ppoffice** [comment]
No plan for that right now. However, you can DIY by inserting the claim either in the footer (https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/common/footer.ejs) or at the end of the article (https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/common/article.ejs).
