### ISSUE TITLE
[Feature Request] Any Plan for Sidebar?

### ISSUE THREAD

**Issue by hyrepo** [ppoffice/hexo-theme-minos#65]
Hi, 

Thanks for such amazing and elegant theme, like it so much. I tried to add a sidebar by myself, so more information could be displayed on main page and saves one click to see things like archives. The feature is quite easy but the style is much difficult for me since I'm not very familiar with UI.

So just kindly ask is there any plan to add sidebar?

**Comment by ppoffice** [comment]
@hyrepo This is a one-column-layout theme, so the sidebar is not in the scope of this project.
