### ISSUE TITLE
Favicon and OpenGraph meta doesn't exist

### ISSUE THREAD

**Issue by Haocen** [ppoffice/hexo-theme-minos#68]
For Favicon:

https://realfavicongenerator.net/favicon_checker?protocol=https&site=blog.zhangruipeng.me%2Fhexo-theme-minos%2F

For OpenGraph:

https://opengraphcheck.com/result.php?url=https%3A%2F%2Fblog.zhangruipeng.me%2Fhexo-theme-minos%2F

**Comment by ppoffice** [comment]
@Haocen The demo site does not have these things.

**Comment by Haocen** [comment]
Mind to share some hint about how user can add them?

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-minos/blob/master/_config.yml.example#L1-L10
