### ISSUE TITLE
Font Awesome Icons Issue

### ISSUE THREAD

**Issue by JoeAsir** [ppoffice/hexo-theme-minos#69]
When I use Icons which name with a hyphen, the icon cannot be shown.
For example, when I use user-times(https://fontawesome.com/icons/user-times?style=solid), the icon cannot be loaded correctly.

**Comment by JoeAsir** [comment]
@ppoffice 
The Icon user-ninja couldn't be present and here is my _config.yml.

# Website's icon url.
favicon: /favicon.ico

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
#logo:
#  text: superAsir's Notes
logo: http://otmy7guvn.bkt.clouddn.com/profile.jpeg

article:
  # Show word count and estimated reading time.
  readtime: true
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: atom-one-light

# Navigation bar menu links.
menu:
  Home: /
  Archives: /archives
#  Tags: /tags
  Categories: /categories
#  Lifestyle: /categories/LifeStyle
#  Music: /categories/Music
#  Technology: /categories/Technology
  About: /about

# Search plugin settings.
search:
  type: insight

# Share plugin settings.
share:
  type: addthis 
  install_url: //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5a694d4d78479a8b

# Comment plugin settings.
comment:
  type: disqus
  shortname: supaerasir

# Other plugins and their settings.
plugins:
  mathjax: true
  gallery: true
  google-analytics:
    tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/JoeAsir
  Twitter:
    icon: fab fa-twitter
    url: https://twitter.com/joe_asir
  Instagram:
    icon: fab fa-instagram
    url: https://www.instagram.com/zhaoyao0560/
  Weibo: 
    icon: fab fa-weibo
    url: https://www.weibo.com/2144484004/profile?topnav=1&wvr=6&is_all=1
  Mail:
    icon: fas fa-envelope
    url: mailto:joeAsir0560@outlook.com
  Best Fellow:
    icon: fas fa-user-ninja
    url: https://www.unbelievable9.info/

# Links at the bottom of the page.
footer_links:
    Best Fellow: https://www.unbelievable9.info/

**Comment by ppoffice** [comment]
@JoeAsir user-ninja was release with FontAwesome 5.0.11 while this theme uses 5.0.8. You can fix this by bumping the version number in this file. https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/common/head.ejs#L45

**Comment by JoeAsir** [comment]
@ppoffice Thanks! It really works.
By the way, I have another question, how to add the table of contents as shown on the navigation bar in the [Documents](https://blog.zhangruipeng.me/hexo-theme-minos/Configuring-Minos/), I have no idea after going through the whole Documents.

**Comment by ppoffice** [comment]
@JoeAsir Add `toc: true` to the front-matter of your post.

https://raw.githubusercontent.com/ppoffice/hexo-theme-minos/site/source/_posts/Configuring-Minos.md

**Comment by JoeAsir** [comment]
Thanks a lot! It's really nice of you helping me solve the problem!
ps. Minos is pretty awesome!
