### ISSUE TITLE
Would it be possible to move the lang button?

### ISSUE THREAD

**Issue by tn710617** [ppoffice/hexo-theme-minos#80]
Hello! I like your theme so much! Would it be possible to move the lang button to somewhere which is more noticeable? Like the top of the screen

**Comment by ppoffice** [comment]
@tn710617 You'll need to edit the layout manually. Please try to move this line:
https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/common/footer.ejs#L27
to somewhere in this file:
https://github.com/ppoffice/hexo-theme-minos/blob/master/layout/common/navbar.ejs

**Comment by tn710617** [comment]
Thanks! I followed your instruction, and got what I want. 
I would suggest to move the menu to somewhere more noticeable, because every time when I visit some page rendered with language I don't know, the first thing I do is look for the language switch menu.
I've build my blog properly, and I really like your Theme. Here is the link to my 
[blog](https://tn710617.github.io/)
