### ISSUE TITLE
Overridding theme config does not work

### ISSUE THREAD

**Issue by draran** [ppoffice/hexo-theme-minos#95]
I cannot override settings from /themes/minos/_config.yml by editing the main /_config.yml file although this should be possible according to the hexo documentation, as described [here](https://hexo.io/docs/configuration.html#Overriding-Theme-Config). Is this intended?

**Comment by ppoffice** [comment]
@draran It's not working that way in Minos. Please try to put your config options without the leading `theme_config:`.
